version: "3.9"

services:
  app:
    image: golang:1.21
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env 
    restart: always
    networks:
      - app_network

networks:
  app_network:
